name: life_track
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  shared_preferences: ^2.5.3
  sizer: ^3.1.3
  font_awesome_flutter: ^10.12.0
  pin_code_fields: ^8.0.1
  flutter_image_compress: ^2.4.0
  charts_flutter: ^0.12.0
  fl_chart: ^1.1.1
  country_picker: ^2.0.27

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/png/
    - assets/images/icons/
    - assets/images/background/
    - assets/images/preferred/
    - assets/images/navbar_icons/
    - assets/images/png/activities/
    - assets/images/png/activities/area_sports/

  fonts:
    - family: redditsans
      fonts:
        - asset: assets/fonts/Reddit_Sans/static/RedditSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Reddit_Sans/static/RedditSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Reddit_Sans/static/RedditSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Reddit_Sans/static/RedditSans-Bold.ttf
          weight: 700
    - family: worksans
      fonts:
        - asset: assets/fonts/Work_Sans/static/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Work_Sans/static/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/Work_Sans/static/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Work_Sans/static/WorkSans-Bold.ttf
          weight: 700
    - family: degular
      fonts:
        - asset: assets/fonts/degular/fonnts.com-DegularDemo-Regular.otf
          weight: 400
        - asset: assets/fonts/degular/fonnts.com-DegularDemo-Medium.otf
          weight: 500
        - asset: assets/fonts/degular/fonnts.com-DegularDemo-Bold.otf
          weight: 700
    #- family: worksans
    #  fonts:
    #    - asset: assets/fonts/Work_Sans/static/WorkSans-Regular.ttf
    #    - asset: assets/fonts/Work_Sans/static/WorkSans-Medium.ttf
    #    - asset: assets/fonts/Work_Sans/static/WorkSans-Italic.ttf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/png/logo.png"
